// Solid Earth Article Monitor - GRL v1
// GRL Vol 53, Issue 11 (published 2026-06-16)
// Auto-generated by solidearth-article-monitor skill

const reports = [
  {
    id: "grl-v53-i11-20260616",
    date: "2026-06-16",
    issue: "Vol 53, Issue 11",
    issueDate: "2026-06-16",
    title: "GRL Solid Earth Article Brief",
    source: "Geophysical Research Letters",
    recommendation: {
      label: "Most Recommended",
      title: "The Role of Mafic Intrusion in Seismotectonics: Insights From the 1668 M 8.5 Tancheng Earthquake Rupture Zone Along the Tan-Lu Fault Zone, Eastern China",
      text: "This article is the only paper in this issue that maps to all three interest keywords - Seismology, Fault Damage Zone, and Crustal Deformation. Using dense-array receiver functions, it reveals how mafic intrusions control crustal heterogeneity, Moho variations, and seismicity along the Tan-Lu Fault Zone, offering fundamental insights into lithosphere-scale fault zone behavior and long-term earthquake hazard in eastern China."
    },
    articles: [
    {
      title: "Lithosphere-Asthenosphere Interactions Across the Indo-Burma Subduction Zone From Sp Receiver Functions",
      topic: "Seismology",
      region: "Indo-Burma Subduction Zone",
      method: "Sp Receiver Functions",
      interestTags: ["Seismology"],
      authors: "Yiming Bai, Xiaohui Yuan, Frederik Tilmann, Bernd Schurr, Yinshuang Ai, Yumei He, Shengji Wei, Guangbing Hou, Myo Thant, Kyaing Sein, Oo Than, Mingming Jiang, Ping Tong",
      keyPoints: ["Sp receiver functions from dense array data reveal a regionally shallow lithosphere-asthenosphere boundary (LAB) at ~70 km depth beneath the northeastern Indian plate margin.", "Beneath the Indo-Burma Ranges, the Indian LAB dips eastward at ~20 degrees down to ~140 km, imaged primarily through SKS-derived receiver functions.", "The dipping LAB geometry provides new constraints on lithosphere-asthenosphere interactions and mantle flow patterns driven by the India-Asia convergence."],
      onlineDate: "2026-06-08",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2025gl121401"
    },
    {
      title: "Paleomagnetic Evidence of Internal Rotation in the Eastern Qiangtang and Its Relation to Distributed Strike-Slip Faulting in the Southeastern Tibetan Plateau",
      topic: "Crustal Deformation",
      region: "Eastern Qiangtang, SE Tibetan Plateau",
      method: "Paleomagnetism",
      interestTags: ["Crustal Deformation"],
      authors: "Wanlong Xu, Maodu Yan, Mathew Domeier, Chong Guan, Qiang Fu, Liang Yu, Zhichao Niu, Miaomiao Shen, Bingshuai Li, Dawen Zhang, Zunbo Xu, Yuwei Zhang",
      keyPoints: ["Paleomagnetic data from Eocene red beds in Baizha reveal ~40 degrees clockwise rotation after the late Eocene, combining regional oroclinal bending and internal block rotation.", "The rotation pattern is linked to distributed strike-slip faulting associated with the India-Eurasia collision in the southeastern Tibetan Plateau.", "Results suggest internal rotation is not limited to the Lanping-Simao Terrane but extends northward into the eastern Qiangtang, refining models of plateau deformation."],
      onlineDate: "2026-06-07",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl122579"
    },
    {
      title: "The Role of Mafic Intrusion in Seismotectonics: Insights From the 1668 M 8.5 Tancheng Earthquake Rupture Zone Along the Tan-Lu Fault Zone, Eastern China",
      topic: "Seismology",
      region: "Tan-Lu Fault Zone, Eastern China",
      method: "Dense-Array Receiver Functions, Vp/Vs Tomography",
      interestTags: ["Seismology", "Fault Damage Zone", "Crustal Deformation"],
      authors: "Yuchen Huang, Huajian Yao, Mengxuan Yan, Shengzhe Zhao, Yichen Pan, Guili Zhou, Bohan Zhang",
      keyPoints: ["Dense-array receiver functions reveal pronounced Moho variations and crustal heterogeneity controlled by the Tan-Lu Fault Zone in the 1668 M 8.5 Tancheng earthquake rupture zone.", "High Vp/Vs ratios and weaker Moho Ps conversions spatially correlate with the eastern fault branch, indicating mafic intrusion as a key seismotectonic factor.", "The study demonstrates that lithosphere-scale fault zones interact with mafic intrusions to influence crustal rheology and long-term seismic activity patterns."],
      onlineDate: "2026-06-06",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl121685"
    },
    {
      title: "The 2025 Mw 7.6 Aomori-Oki Megathrust Sequence and a Slip-Parallel Seismic Belt to the Trench",
      topic: "Seismology",
      region: "Aomori-Oki, Japan Trench",
      method: "Waveform Inversion, High-Precision Relocation",
      interestTags: ["Seismology", "Crustal Deformation"],
      authors: "Keisuke Yoshida, Masaoki Uno, Dan Bassett",
      keyPoints: ["Waveform inversion of the 2025 Mw 7.6 Aomori-Oki earthquake reveals large slip (>1 m) extending ~40 km northward from the hypocenter, overlapping the inferred 1968 Mw 8.3 Tokachi-Oki asperity.", "High-precision relocations show major aftershocks clustered near minor secondary slip zones (0.2-0.6 m) ~60 km updip, forming streaks aligned with plate convergence.", "The 2025 sequence and historical M >= 5 events delineate a slip-parallel seismic belt extending trenchward across a prominent tremor gap, suggesting structural heterogeneity from subducting plate roughness."],
      onlineDate: "2026-06-06",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl122361"
    },
    {
      title: "Late Carboniferous Paleomagnetism From North Qiangtang Block Reveals a Multibranched Paleo-Tethys Ocean",
      topic: "Crustal Deformation",
      region: "North Qiangtang Block, Tethyan Realm",
      method: "Paleomagnetism, Geochronology",
      interestTags: ["Crustal Deformation"],
      authors: "Jiahui Zhang, Xin Cheng, Zhongshan Shen, Daniel Pastor‐Galán, Bitian Wei, Longyun Xing, Dongmeng Zhang, Nan Jiang, Mengting Zhong, Shuqi Lan, Muhammad Rizwan, Chenglong Deng, Hanning Wu",
      keyPoints: ["Late Carboniferous paleomagnetic and geochronological data from the Walongshan Formation provide an absolute-age-constrained paleomagnetic pole for the North Qiangtang Block.", "Results reveal a multibranched Paleo-Tethys Ocean configuration, challenging previous single-ocean or simple-branch models of Tethyan evolution.", "The new paleogeographic reconstruction constrains the position and drift history of the North Qiangtang Block within the eastern Paleo-Tethys during the Late Paleozoic."],
      onlineDate: "2026-06-03",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl123015"
    },
    {
      title: "Crustal Deformation and Gravitational Effects From Dynamic Ocean Mass Redistribution Impact Projected Sea-Level Change",
      topic: "Crustal Deformation",
      region: "Global (CMIP6 projections)",
      method: "CMIP6 Climate Model Analysis, Sea-Level Projections",
      interestTags: ["Crustal Deformation"],
      authors: "Grace Ertel, Sophie Coulson, Christopher G. Piecuch, Matthew Hoffman",
      keyPoints: ["Dynamic ocean mass redistribution under climate warming induces crustal deformation and gravitational effects that amplify projected ocean-dynamic sea-level patterns through 2100.", "Using CMIP6 climate model output, the study quantifies relative sea-level changes from gravitational self-attraction, solid Earth deformation, and Earth rotation axis shifts (GRD effects).", "GRD effects from ocean-dynamic mass loading represent a non-negligible correction to sea-level projections, currently not incorporated in standard assessments."],
      onlineDate: "2026-06-03",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl122243"
    },
    {
      title: "The Effect of Hydraulic Fracturing on the 2021 Ms 6.0 Luxian Earthquake as Revealed by Deformation and Numerical Simulations",
      topic: "Seismology",
      region: "Luxian, Sichuan Basin, China",
      method: "InSAR Time-Series, Poroelastic Modeling",
      interestTags: ["Seismology", "Crustal Deformation"],
      authors: "Xiaoran Fan, Guohong Zhang, Yosuke Aoki, Xinjian Shan",
      keyPoints: ["Multi-temporal InSAR analysis of Sentinel-1 data reveals coseismic deformation from the 2021 Ms 6.0 Luxian earthquake and localized uplift near hydraulic fracturing platforms.", "Three-dimensional poroelastic modeling shows that cumulative water injection from multiple platforms produced sufficient pore-pressure changes and stress perturbations to affect the seismogenic fault.", "Results provide quantitative evidence linking hydraulic fracturing activities to moderate earthquake occurrence in the Sichuan Basin, with implications for induced seismicity hazard assessment."],
      onlineDate: "2026-06-03",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2025gl120854"
    },
    {
      title: "Complex Shallow Unilateral Rupture of the 2025 M w 7.0 Hubbard Glacier Earthquake Terminated by a Restraining Bend on the Connector Fault",
      topic: "Seismology",
      region: "Connector Fault, Alaska-Canada Border",
      method: "Finite-Fault Modeling, Bayesian Inversion, Hypocenter Relocation",
      interestTags: ["Seismology", "Crustal Deformation"],
      authors: "Mohammadreza Jamalreyhani, Fenglin Niu, Simone Cesca, Eric Bergman",
      keyPoints: ["The 6 December 2025 Mw 7.0 Hubbard Glacier earthquake exhibited complex shallow unilateral rupture, nucleating as right-lateral strike-slip and propagating northwestward.", "Bootstrap and Bayesian-based probabilistic finite-fault inversions constrained by hypocenter relocations and moment tensor solutions reveal rupture terminated by a restraining bend.", "The Connector fault geometry and rupture behavior provide new insights into fault segmentation and earthquake hazard at the Alaska-Canada border."],
      onlineDate: "2026-06-02",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl122036"
    },
    {
      title: "Integrated Geophysical Imaging Reveals the Origin and Pathways of Mantle-Derived CO 2 Beneath the Tangra Yumco Rift, Central Tibet",
      topic: "Seismology",
      region: "Tangra Yumco Rift, Central Tibet",
      method: "Receiver Function Analysis, S-Wave Velocity Inversion, tomoDD Tomography",
      interestTags: ["Seismology", "Crustal Deformation"],
      authors: "Zongxu Li, Rizheng He, Hanhan Tang, Qiang Xu, Lei Gao, Yulan Li, Lihui Tan, Xiao Niu, Ruo Jia",
      keyPoints: ["High-resolution crust-mantle imaging reveals a vertical Crust-Mantle Degassing System beneath the Tangra Yumco Rift, bounded by the Zhala and Wozang Faults.", "Two mantle low-velocity zones at ~70 km depth are interpreted as remnants of the Neo-Tethys and Shiquanhe-Jiali Tethys oceanic slabs, sourcing mantle-derived CO2.", "Crustal low-velocity zones (20-40 km, Vs < 3.5 km/s) correlate with high-conductivity bodies, suggesting partial melt and fluid pathways that feed the rift's hydrothermal system."],
      onlineDate: "2026-05-30",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl121927"
    },
    {
      title: "Shallow Modeling and Site-Amplification From Telecommunications Fibers in Istanbul",
      topic: "Seismology",
      region: "Istanbul, Turkiye",
      method: "DAS (Distributed Acoustic Sensing), Ambient Noise Tomography",
      interestTags: ["Seismology"],
      authors: "Daniel Bowden, Ali Shaikhsulaiman, Simon Grieder, Ebru Bozdağ, Ali Özgün Konca, Semih Ergintav, Esra Ertan, Evrim Yavuz, Muhammed Ünlü, Andreas Fichtner",
      keyPoints: ["Pre-existing telecommunications fibers in Istanbul were used with ambient noise from urban traffic to generate a seismic velocity model down to 100 m depth along an 8 km profile.", "Rayleigh wave dispersion curves extracted via DAS were inverted using a trans-dimensional Monte-Carlo algorithm to estimate shear wave velocities consistent with local geology.", "Site-amplification estimates derived from the velocity model provide critical input for seismic hazard assessment in a megacity located near the North Anatolian Fault."],
      onlineDate: "2026-05-30",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2025gl121011"
    },
    {
      title: "Interseismic Creep Along the Enriquillo-Plantain Garden Fault, Haiti, Estimated From InSAR",
      topic: "Crustal Deformation",
      region: "Enriquillo-Plantain Garden Fault, Haiti",
      method: "PS+DS InSAR Time-Series",
      interestTags: ["Crustal Deformation"],
      authors: "Rishabh Dutta, Jeremy L. Maurer, Yi‐Chieh Lee",
      keyPoints: ["PS+DS InSAR time-series analysis of Sentinel-1 data (2017-2021) overcomes decorrelation in highly vegetated terrain to reveal interseismic creep along the Enriquillo-Plantain Garden Fault.", "Shallow creep rates are mapped along the EPGF and adjacent faults, providing constraints on strain accommodation near the 2021 Mw 7.1 Nippes earthquake rupture zone.", "The interseismic slip distribution helps refine seismic hazard models for southern Haiti, where complex fault interactions pose significant risk."],
      onlineDate: "2026-05-30",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2025gl119670"
    },
    {
      title: "Fluid-Induced Magnetic Enhancement in Sandstone Friction Experiments: Implications for Coseismic Fault Temperature Estimates",
      topic: "Fault Damage Zone",
      region: "Groningen Gas Field, Netherlands (Slochteren Sandstone)",
      method: "Rotary-Shear Friction Experiments, Rock Magnetism",
      interestTags: ["Fault Damage Zone"],
      authors: "Qiang Fu, Mark J. Dekkers, Simo Spassov, Derya Gürer, Chien‐Cheng Hung, Job P. B. Arts, André R. Niemeijer",
      keyPoints: ["First experimental investigation of fluid effects on friction-induced magnetic mineral alteration using rotary-shear experiments on Slochteren Sandstone gouges at seismic slip rates (5 cm/s).", "Fluid-saturated conditions significantly enhance magnetic susceptibility changes compared to dry experiments, with implications for interpreting coseismic temperature estimates from fault rock magnetism.", "Results caution that fluid presence can bias rock-magnetic paleothermometry, requiring correction when constraining earthquake energy budgets and fault weakening mechanisms."],
      onlineDate: "2026-05-28",
      issueDate: "2026-06-16",
      link: "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2026gl121692"
    }
    ]
  }
];
